/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class lap3 extends javax.swing.JFrame {

    /**
     * Creates new form lap3
     */
    public lap3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPfull = new java.awt.Panel();
        JPtren = new java.awt.Panel();
        label1 = new java.awt.Label();
        JPcuoi = new java.awt.Panel();
        label2 = new java.awt.Label();
        JPgiua = new java.awt.Panel();
        s15 = new java.awt.Button();
        s14 = new java.awt.Button();
        s13 = new java.awt.Button();
        s12 = new java.awt.Button();
        s11 = new java.awt.Button();
        so10 = new java.awt.Button();
        so9 = new java.awt.Button();
        so8 = new java.awt.Button();
        so7 = new java.awt.Button();
        so6 = new java.awt.Button();
        so5 = new java.awt.Button();
        so4 = new java.awt.Button();
        so3 = new java.awt.Button();
        so2 = new java.awt.Button();
        so1 = new java.awt.Button();
        trống = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPfull.setLayout(new java.awt.BorderLayout());

        JPtren.setBackground(new java.awt.Color(153, 204, 255));

        label1.setForeground(new java.awt.Color(255, 51, 51));
        label1.setText("TRÒ CHƠI XẾP Ô SỐ");
        JPtren.add(label1);

        JPfull.add(JPtren, java.awt.BorderLayout.NORTH);

        JPcuoi.setBackground(new java.awt.Color(204, 255, 204));

        label2.setText("Bắt đầu");
        JPcuoi.add(label2);

        JPfull.add(JPcuoi, java.awt.BorderLayout.SOUTH);

        JPgiua.setLayout(new java.awt.GridLayout(4, 4));

        s15.setLabel("15");
        JPgiua.add(s15);

        s14.setLabel("14");
        JPgiua.add(s14);

        s13.setLabel("13");
        JPgiua.add(s13);

        s12.setLabel("12");
        JPgiua.add(s12);

        s11.setLabel("11");
        JPgiua.add(s11);

        so10.setLabel("10");
        JPgiua.add(so10);

        so9.setLabel("9");
        JPgiua.add(so9);

        so8.setLabel("8");
        JPgiua.add(so8);

        so7.setLabel("7");
        JPgiua.add(so7);

        so6.setLabel("6");
        JPgiua.add(so6);

        so5.setLabel("5");
        JPgiua.add(so5);

        so4.setLabel("4");
        JPgiua.add(so4);

        so3.setLabel("3");
        JPgiua.add(so3);

        so2.setLabel("2");
        JPgiua.add(so2);

        so1.setLabel("1");
        JPgiua.add(so1);
        JPgiua.add(trống);

        JPfull.add(JPgiua, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPfull, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPfull, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lap3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel JPcuoi;
    private java.awt.Panel JPfull;
    private java.awt.Panel JPgiua;
    private java.awt.Panel JPtren;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Button s11;
    private java.awt.Button s12;
    private java.awt.Button s13;
    private java.awt.Button s14;
    private java.awt.Button s15;
    private java.awt.Button so1;
    private java.awt.Button so10;
    private java.awt.Button so2;
    private java.awt.Button so3;
    private java.awt.Button so4;
    private java.awt.Button so5;
    private java.awt.Button so6;
    private java.awt.Button so7;
    private java.awt.Button so8;
    private java.awt.Button so9;
    private java.awt.Button trống;
    // End of variables declaration//GEN-END:variables
}
