/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mmt11.tuan3;

/**
 *
 * @author Dell
 */
public class DEMOtinhtoan extends javax.swing.JFrame {

    /**
     * Creates new form DEMOtinhtoan
     */
    public DEMOtinhtoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        JPtren = new javax.swing.JPanel();
        tieude = new javax.swing.JButton();
        jPcuoi = new javax.swing.JPanel();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        jPgiua = new javax.swing.JPanel();
        thaotac = new javax.swing.JPanel();
        tacvu = new javax.swing.JButton();
        giai = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        thoat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        nhâp = new javax.swing.JLabel();
        nhapb = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        pheptoan = new javax.swing.JLabel();
        cong = new javax.swing.JRadioButton();
        nhan = new javax.swing.JRadioButton();
        tru = new javax.swing.JRadioButton();
        chia = new javax.swing.JRadioButton();
        so6 = new javax.swing.JButton();
        so7 = new javax.swing.JButton();
        ketqua = new javax.swing.JLabel();
        xuatkqua = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPtren.setBackground(new java.awt.Color(255, 255, 51));

        tieude.setBackground(new java.awt.Color(255, 153, 51));
        tieude.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tieude.setForeground(new java.awt.Color(255, 0, 204));
        tieude.setText("CỘNG TRỪ NHÂN CHIA");
        tieude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tieudeActionPerformed(evt);
            }
        });
        JPtren.add(tieude);

        getContentPane().add(JPtren, java.awt.BorderLayout.PAGE_START);

        jPcuoi.setBackground(new java.awt.Color(204, 204, 255));
        jPcuoi.setForeground(new java.awt.Color(255, 153, 153));

        c1.setBackground(new java.awt.Color(204, 0, 51));
        c1.setForeground(new java.awt.Color(204, 0, 0));

        c2.setBackground(new java.awt.Color(255, 102, 102));
        c2.setForeground(new java.awt.Color(102, 255, 102));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        c3.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPcuoiLayout = new javax.swing.GroupLayout(jPcuoi);
        jPcuoi.setLayout(jPcuoiLayout);
        jPcuoiLayout.setHorizontalGroup(
            jPcuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcuoiLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(c1)
                .addGap(35, 35, 35)
                .addComponent(c2)
                .addGap(35, 35, 35)
                .addComponent(c3)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPcuoiLayout.setVerticalGroup(
            jPcuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcuoiLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPcuoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jPcuoi, java.awt.BorderLayout.PAGE_END);

        jPgiua.setBackground(new java.awt.Color(255, 51, 51));

        thaotac.setToolTipText("");
        thaotac.setName("Tác Vụ"); // NOI18N

        tacvu.setForeground(new java.awt.Color(255, 0, 51));
        tacvu.setText("Tác Vụ");

        giai.setForeground(new java.awt.Color(0, 102, 204));
        giai.setText("Giải");
        giai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaiActionPerformed(evt);
            }
        });

        xoa.setForeground(new java.awt.Color(0, 51, 51));
        xoa.setText("Xóa");

        thoat.setForeground(new java.awt.Color(255, 102, 102));
        thoat.setText("Thoát");

        javax.swing.GroupLayout thaotacLayout = new javax.swing.GroupLayout(thaotac);
        thaotac.setLayout(thaotacLayout);
        thaotacLayout.setHorizontalGroup(
            thaotacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thaotacLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thaotacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tacvu)
                    .addGroup(thaotacLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(thaotacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xoa)
                            .addComponent(giai))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thaotacLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thoat)
                .addContainerGap())
        );
        thaotacLayout.setVerticalGroup(
            thaotacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thaotacLayout.createSequentialGroup()
                .addComponent(tacvu)
                .addGap(4, 4, 4)
                .addComponent(giai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thoat)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        nhâp.setText("nhập a:");

        nhapb.setText("nhập b:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nhapb)
                    .addComponent(nhâp))
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(nhâp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nhapb)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 255, 153));

        pheptoan.setText("Phép Toán");

        cong.setSelected(true);
        cong.setText("Cộng");

        nhan.setText("Nhân");

        tru.setText("Trừ");

        chia.setText("Chia");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(nhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chia))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tru)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pheptoan)
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pheptoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cong)
                    .addComponent(tru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhan)
                    .addComponent(chia))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        so6.setText("6");

        so7.setText("7");

        ketqua.setText("Kết Quả:");

        xuatkqua.setText("13");

        javax.swing.GroupLayout jPgiuaLayout = new javax.swing.GroupLayout(jPgiua);
        jPgiua.setLayout(jPgiuaLayout);
        jPgiuaLayout.setHorizontalGroup(
            jPgiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPgiuaLayout.createSequentialGroup()
                .addComponent(thaotac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPgiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPgiuaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPgiuaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPgiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(so6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(so7, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))))
                .addGap(58, 58, 58))
            .addGroup(jPgiuaLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(ketqua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xuatkqua, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPgiuaLayout.setVerticalGroup(
            jPgiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPgiuaLayout.createSequentialGroup()
                .addComponent(thaotac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPgiuaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPgiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ketqua)
                    .addComponent(xuatkqua))
                .addGap(43, 43, 43))
            .addGroup(jPgiuaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(so6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(so7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        getContentPane().add(jPgiua, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void tieudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tieudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tieudeActionPerformed

    private void giaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEMOtinhtoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEMOtinhtoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEMOtinhtoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEMOtinhtoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DEMOtinhtoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPtren;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JRadioButton chia;
    private javax.swing.JRadioButton cong;
    private javax.swing.JButton giai;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPcuoi;
    private javax.swing.JPanel jPgiua;
    private javax.swing.JLabel ketqua;
    private javax.swing.JRadioButton nhan;
    private javax.swing.JLabel nhapb;
    private javax.swing.JLabel nhâp;
    private javax.swing.JLabel pheptoan;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton tacvu;
    private javax.swing.JPanel thaotac;
    private javax.swing.JButton thoat;
    private javax.swing.JButton tieude;
    private javax.swing.JRadioButton tru;
    private javax.swing.JButton xoa;
    private javax.swing.JButton xuatkqua;
    // End of variables declaration//GEN-END:variables
}
